sudo: required
service:
  - docker

before_install:
  - docker build -t hkusanic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hkusanic/react-test npm test -- --coverage

after_success:
  - docker build -t hkusanic/multi-client ./client
  - docker build -t hkusanic/multi-nginx ./nginx
  - docker build -t hkusanic/multi-server ./server
  - docker build -t hkusanic/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASWORD" | docker login -u "$DOCKER_ID" --password-stdin # echo will get password and emit it to the right hand sid of the pipe
  # Take those images and push them to docker hub
  - docker push hkusanic/multi-client
  - docker push hkusanic/multi-nginx
  - docker push hkusanic/multi-server 
  - docker push hkusanic/multi-worker